name: Selenium Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows running manually
  schedule:
    - cron: '0 0 * * *'  # Run every day at 00:00 UTC

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    env:
      DEV_URL: ${{ vars.DEV_URL }}
      STAG_URL: ${{ vars.STAG_URL }}

    permissions:
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install project dependencies (Poetry)
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry --version
          poetry install --no-interaction --no-ansi

      - name: Prepare reports directory
        run: |
          mkdir -p reports

      - name: Prepare reports directory
        run: |
          mkdir -p reports

      - name: Run sample pytest
        run: |
         pytest tests/test_sample.py
        continue-on-error: true

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: reports/test-results.xml
          retention-days: 1